language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

#notifications:
  #slack: cs329e-fall-2017:TWFzxBtOzsFmRkNjOTyP3bXA

install:
     - pip install --upgrade pip
     - pip --version
     - pip install -r requirements.txt

script:
    - python test.py