language: python

python:
   - "3.5"

before_install:
    - pip install --upgrade pip

#notifications:
  #slack: cs329e-fall-2017:TWFzxBtOzsFmRkNjOTyP3bXA

addons:
    postgresql: "9.5"

services:
  - postgresql

install:
     - pip install --upgrade pip
     - pip --version
     - pip install -r requirements.txt
     
before_script:
     - psql -c 'create database digitalbinding;' -U postgres

script:
    - python test.py