runtime: python
threadsafe: yes
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:cs329e@/digitalbinding?host=/cloudsql/digitalbinding:us-central1:digitalbindingdb
beta_settings:
    cloud_sql_instances: digitalbinding:us-central1:digitalbindingdb

handlers:
- url: /.*
  script: app.app